config/routes.rb
Timeline::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  resources :histories

   root 'histories#index'

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/history.rb
class History < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  # GET /histories
  # GET /histories.json

  def index
    @histories = History.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: json_out = {
        "timeline"=>
        {
          "headline"=>"Timeline of European Medieval Philosophy",
          "type"=>"default",
          "text"=>"<p>History of Medieval Philosophy in <b>Europe</b></p>",
          "asset"=> {
          "media"=>"http://www.iep.utm.edu/wp-content/media/anselm.jpg",
          "credit"=>"Anselm of Canterbury",
          "caption"=>"Famous European Medieval Philosophers"
        },

          "date"=> @histories.map { |timeline| {"startDate" => timeline.startdate.strftime("%Y,%m,%d"),"endDate" => timeline.enddate.strftime("%Y,%m,%d"),"headline" => timeline.headline,"text" => timeline.content, "asset" => {"media" => timeline.media}}},


          "era"=> [
            {
          "startDate"=>"1000,01,01",
          "endDate"=>"1300,01,01",
          "headline"=>"Timeline of European Medieval Philosophy",
          "text"=>"<p>History of Medieval Philosophy in Europe</p>",
          "tag"=>"Philosophy Rocks!"
        }

        ]
        }
      } }
    end
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render action: 'show', status: :created, location: @history }
      else
        format.html { render action: 'new' }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_history
    @history = History.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def history_params
    params.require(:history).permit(:startdate, :enddate, :content, :headline, :media, :mediacaption, :mediacredit)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/histories/_form.html.erb
<%= form_for @history, :html => {:class => "horizontal-form", :role => "form"} do |f| %>
  <% if @history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
      <% @history.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :startdate %>
    <%= f.date_select :startdate, {:start_year => Time.now.year - 100, :end_year => Time.now.year} %>
  </div>
  <div class="form-group">
    <%= f.label :enddate %>
    <%= f.date_select :enddate %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>
  <div class="form-group">
    <%= f.label :headline %>
    <%= f.text_field :headline %>
  </div>
  <div class="form-group">
    <%= f.label :media, "Youtube/Vimeo URL" %>
    <%= f.text_field :media %>
  </div>
  <div class="form-group">
    <%= f.label :mediacaption %>
    <%= f.text_field :mediacaption %>
  </div>
  <div class="form-group">
    <%= f.label :mediacredit %>
    <%= f.text_field :mediacredit %>
  </div>
  <div class="actions">
    <%= f.submit "Create Timeline", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/histories/edit.html.erb
<h1>Editing history</h1>

<%= render 'form' %>

<%= link_to 'Show', @history %> |
<%= link_to 'Back', histories_path %>

app/views/histories/index.html.erb
<h5>Timeline Header</h5>

<%= link_to 'Create Timeline', new_history_path, :class => "btn btn-primary" %>
<br />

<br />
<script>
  $(document).ready(function() {
    createStoryJS({
      type:       'timeline',
      width:      '1200',
      height:     '500',
      source:     '<%= @histories %>',
      //source:	  './philosophers.json',
      embed_id:   'my-timeline',
      start_at_end:       false,  
      start_at_slide:     '1',                           
      start_zoom_adjust:  '-3',   
      hash_bookmark:      true,  
      //font:               'Bevan-PotanoSans',  
      debug:              true,   
      lang:               'ru',   
      maptype:            'watercolor'                
    });
  });
</script>
<div id="my-timeline"></div>

app/views/histories/new.html.erb
<h1>New history</h1>

<%= render 'form' %>

<%= link_to 'Back', histories_path %>

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Startdate:</strong>
  <%= @history.startdate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @history.enddate %>
</p>

<p>
  <strong>Content:</strong>
  <%= @history.content %>
</p>

<p>
  <strong>Headline:</strong>
  <%= @history.headline %>
</p>

<p>
  <strong>Media:</strong>
  <%= @history.media %>
</p>

<p>
  <strong>Mediacaption:</strong>
  <%= @history.mediacaption %>
</p>

<p>
  <strong>Mediacredit:</strong>
  <%= @history.mediacredit %>
</p>

<%= link_to 'Edit', edit_history_path(@history) %> |
<%= link_to 'Back', histories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Timeline" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <!-- <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script> -->
    <script type="text/javascript"  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBIEqDYrMzPK2tgY21B8qXU7jLqfGPY97A&sensor=false"> </script>
    <!-- <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>  -->
    <script type="text/javascript">
      function initialize() {
        var mapOptions = {
          center: new google.maps.LatLng(44.397, 0.0),
          zoom: 8
        };
        var map = new google.maps.Map(document.getElementById("map-canvas"),
            mapOptions);
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>


  </head>
  <body>

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to "Medievel Philosophy Timeline", root_url, :class => "brand" %>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Browse Philosophers", 'histories/index' %></li>
            <li><%= link_to "History", 'histories#index' %></li>
            <li><%= link_to "Contact Us", 'pages#contact' %></li>
            <li><%= link_to "About Us", 'pages#about' %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>


    <div class="container">
    
          <%= yield %>

      <footer>
        <p>Copyright &copy; 2014</p>
      </footer>

    </div> 

  </body>
</html>

app/views/pages/about.html.erb
 <div class="row">
        <div class="col-md-12">
          <%= bootstrap_flash %>
        </div>
    </div>
      <div class="row">
        <div col-md-12>
<div id="map-canvas"></div>
        </div>
        </div>


        <p><%= t('about.main_text') %></p>
<h1><%= t('description') %></h1>
<p><%= t('homepage.main_text') %></p>
<p><%= t('services.main_text') %></p>
<a name="cs">Consulting Services</a>
<div>Business Process Analysis<br>
Web Strategy Consulting<br>Web and Mobile Infrastructure</div>
<a name="ad">Web Application Developemnt</a>
<div>Branding and StyleGuide Development<br>Graphic and Logo Design<br>Mobile Design<br>Web Developemnt<br>Quality Assurance Testing</div>
<a name="ux">User Experience Research</a>
<div>User Experience Analysis<br>
Information Architecture<br>							
Wireframes, Mockups and Rapid Prototyping<br>
Content Strategy Analysis</div>

app/views/pages/contact.html.erb
<p><%= t('contact.main_text') %></p>
<form>
  <div>
		<div>
			<label><%= t('contact.form_labels.first_name') %></label>
			<input type="text" placeholder="<%= t('contact.form_labels.first_name') %>">
			<label><%= t('contact.form_labels.last_name') %></label>
			<input type="text" placeholder="<%= t('contact.form_labels.last_name') %>">
			<label><%= t('contact.form_labels.email') %></label>
			<input type="text" placeholder="<%= t('contact.form_labels.email') %>">
		</div>
		<div>
			<label><%= t('contact.form_labels.message') %></label>
			<textarea name="message" id="message" rows="5" placeholder="<%= t('contact.form_labels.message') %>"></textarea>
		</div>
		<div>	
			<button type="submit"><%= t('contact.form_labels.send') %></button>
		</div>
	</div>
</form>